# GraphQL API entitys
type TimeTableOnWeek
{
    StartDay: Date
    Group: Group

    Monday: TimeTableOnDay
    Tuesday: TimeTableOnDay
    Wensday: TimeTableOnDay
    Thusdat: TimeTableOnDay
    Friday: TimeTableOnDay
    Saturday: TimeTableOnDay
}
type TimeTableOnDay
{
    Group: Group
    FirstLesson: Lesson
    SecondLesson: Lesson
    ThidthLesson: Lesson
    FourthLesson: Lesson
    FiveLesson: Lesson
}
interface Person
{
    Id: ID
    name: FullName
}
type Student implements Person
{
    Id: ID
    name: FullName
    Group: Group
    Role: StudentRole
}
type Teacher implements Person
{
    Id: ID
    name: FullName
}
enum StudentRole
{
    Base
    Corrector
    Admin
    SubAdmin
}
type Group
{
    Id: ID
    Name: string
    Course: int
    Speciality: string
}
type FullName
{
    firstName: string
    middleName: string
    lastName: string
}
type Lesson
{
    Date: Date
    Subject: string
    Teacher: Teacher
    LessonType: LessonType
    Location: Location
    Comments: [Comment]!
}
type Comment
{
    Sender: User
    Date: Date
    Message: string
}
type Location
{
    CampusNumber: int
    FloorNumber: int
    CabinetNumber: int
}
enum LessonType
{
    Lection
    Practic
    LaboratorWork
    Seminar
    ControlWork
    Exam
}
type Unpassing
{
    student: Student!
    DateOfInforming: Date!
    Reason: UnpassingReason!
    Lessons: [Lesson]!
}
type UnpassingReason
{
    title: string,
    IsRelatiableReason: Boolean
    needAprouvingDocument: Boolean
}