type Query
{
    Users : [User]!
    Groups : [Group]!

    Auntificate : ActionResponse!

    TimeTableOnWeek(StartDay: Date Group: Group) : TimeTableOnWeek!
    TimeTableOnWeek(EndDay: Date Group: Group) : TimeTableOnWeek!
    TimeTableOnWeek(id: ID Group: Group) : TimeTableOnWeek!
    
    TimeTableOnDay(Day: Date Group: Group) : TimeTableOnDay!

}